Models/Final.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace FinalExam.Models
{
    public class Auction
    {
        [Key]
        public int auction_id { get; set; }

        [RequiredAttribute]
        [MinLength(4)]
        [Display(Name="Product Name")]
        public string product_name { get; set; }

        [RequiredAttribute]
        [Display(Name="Starting Bid")]
        [Range(1, Int32.MaxValue)]
        public int starting_bid { get; set; }

        [RequiredAttribute]
        [MinLength(10)]
        [Display(Name="Product Description")]
        public string product_description { get; set; }

        [RequiredAttribute]
        [FutureDate]
        [Display(Name="End Date")]
        public DateTime end_date { get; set; }

        public int user_id { get; set; }
        public User creator {get;set;}
        public int highest_bid { get; set; }
        public int highest_bidder_id { get; set; }

        public DateTime created_at { get; set; } = DateTime.Now;
        public DateTime updated_at { get; set; } = DateTime.Now;
    }
    public class Bid
    {
        [RequiredAttribute]
        [Range(1, Int32.MaxValue)]
        public int amount { get; set; }
    }
    public class FutureDateAttribute : ValidationAttribute
    {
        protected override ValidationResult IsValid(object value, ValidationContext validationContext)
        {
            if(!(value is DateTime))
            {
                return new ValidationResult("Not a valid date.");
            }
                
            DateTime date = Convert.ToDateTime(value);

            if(date < DateTime.Now)
            {
                return new ValidationResult("Date must be a future date.");
            }

            return ValidationResult.Success;

        }
    }
}

Controllers/FinalController.cs
using Microsoft.EntityFrameworkCore;
using FinalExam.Models;
using System.Linq;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using System;
namespace FinalExam.Controllers
{
    public class FinalController : Controller
    {
        private FinalContext dbContext;
    
        public FinalController(FinalContext context)
        {
            dbContext = context;
        }

        [HttpGet("")]
        public IActionResult Index()
        {
            ViewBag.UserId = HttpContext.Session.GetInt32("UserId");
            if(ViewBag.UserId == null)
            {
                return RedirectToAction("Index", "Logins");
            }
            ViewBag.Wallet = dbContext.Users.Where(u => u.user_id == HttpContext.Session.GetInt32("UserId")).First().wallet;

            var AllAuctions = dbContext.Auctions
                .Include(auction => auction.creator)
                .OrderByDescending(auction => auction.created_at).ToList();

            // this will process auctions
            foreach(var auction in AllAuctions)
            {
                if((int)(DateTime.Now - auction.created_at).TotalDays < 0)
                {
                    if(auction.highest_bidder_id != 0)// Only if somebody has placed a bid, will it continue
                    {
                        var bidder = dbContext.Users.FirstOrDefault(u => u.user_id == auction.highest_bidder_id);
                        auction.creator.wallet += auction.highest_bid;
                        bidder.wallet -= auction.highest_bid;
                    }
                    dbContext.Auctions.Remove(auction);
                    dbContext.SaveChanges();
                }
            }
            // auctions have been processed, grab remaining

            AllAuctions = dbContext.Auctions
                .Include(auction => auction.creator)
                .OrderByDescending(auction => auction.created_at).ToList();
            return View(AllAuctions);
        }

        [HttpGet("CreateAuction")]
        public IActionResult CreateAuction()
        {
            ViewBag.UserId = HttpContext.Session.GetInt32("UserId");
            if(ViewBag.UserId == null)
            {
                return RedirectToAction("Index", "Logins");
            }

            return View("CreateAuction");
        }

        [HttpPost("AddAuction")]
        public IActionResult AddAuction(Auction NewAuction)
        {
            if(ModelState.IsValid)
            {
                int? UserId = HttpContext.Session.GetInt32("UserId");
                if(UserId == null)
                {
                    return View("Index", "Logins");
                }
                NewAuction.user_id = (int)UserId;
                NewAuction.highest_bid = NewAuction.starting_bid;// The platform does not mention having the starting bid override the highest bid to start
                dbContext.Auctions.Add(NewAuction);
                dbContext.SaveChanges();
                return RedirectToAction("Index");
            }
            return View("CreateAuction");
        }

        [HttpGet("DeleteAuction/{ToDelete}")]
        public IActionResult DeleteAuction(int ToDelete)
        {
            int? UserId = HttpContext.Session.GetInt32("UserId");
            ViewBag.UserId = UserId;
            if(ViewBag.UserId == null)
            {
                return RedirectToAction("Index", "Logins");
            }
            var DelAuction = dbContext.Auctions.FirstOrDefault(a => a.auction_id == ToDelete);
            if(DelAuction.user_id == UserId)
            {
                dbContext.Auctions.Remove(DelAuction);
                dbContext.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        [HttpGet("ViewAuction/{ToView}")]
        public IActionResult ViewAuction(int ToView)
        {
            ViewBag.UserId = HttpContext.Session.GetInt32("UserId");
            if(ViewBag.UserId == null)
            {
                return RedirectToAction("Index", "Logins");
            }
            HttpContext.Session.SetInt32("Viewing", ToView);
            var ViewAuction = dbContext.Auctions
                .Include(auction => auction.creator)
                .FirstOrDefault(auction => auction.auction_id == ToView);
            ViewBag.HighestBidder = dbContext.Users.FirstOrDefault(u => u.user_id == ViewAuction.highest_bidder_id);
            ViewBag.ViewAuction = ViewAuction;
            return View("ViewAuction");
        }

        [HttpPost("SubmitBid")]
        public IActionResult SubmitBid(Bid NewBid)
        {
            int? Viewing = HttpContext.Session.GetInt32("Viewing");
            if(ModelState.IsValid)
            {
                int? UserId =HttpContext.Session.GetInt32("UserId");
                ViewBag.UserId = UserId;
                if(ViewBag.UserId == null)
                {
                    return RedirectToAction("Index", "Logins");
                }
                var ViewAuction = dbContext.Auctions
                    .Include(auction => auction.creator)
                    .FirstOrDefault(auction => auction.auction_id == (int)Viewing);
                decimal UserWallet = dbContext.Users.FirstOrDefault(u => u.user_id == UserId).wallet;
                if(NewBid.amount > ViewAuction.highest_bid && NewBid.amount < UserWallet)
                {
                    ViewAuction.highest_bid = NewBid.amount;
                    ViewAuction.highest_bidder_id = (int)HttpContext.Session.GetInt32("UserId");
                    dbContext.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            return RedirectToAction("ViewAuction", new { ToView = Viewing });
        }
    }
}

Views/Final/CreateAuction.cshtml
@model Auction
<form asp-action="AddAuction" asp-controller="Final" method="POST">
    <span asp-validation-for="product_name" class="form_errors"></span>
    <label asp-for="product_name">Product Name:</label>
    <input asp-for="product_name">

    <span asp-validation-for="starting_bid" class="form_errors"></span>
    <label asp-for="starting_bid">Starting Bid:</label>
    <input asp-for="starting_bid">

    <span asp-validation-for="product_description" class="form_errors"></span>
    <label asp-for="product_description">Product Description:</label>
    <input asp-for="product_description">
    
    <span asp-validation-for="end_date" class="form_errors"></span>
    <label asp-for="end_date">End Date:</label>
    <input asp-for="end_date" type="date">

    <button type="submit">Submit</button>
</form>

Views/Final/Index.cshtml
@model IEnumerable<Auction>
<a href="CreateAuction" class="button">Create Auction</a>
<p>Your Balance: $@ViewBag.Wallet</p>
<table>
    <thead>
        <tr>
            <th>Product Name</th>
            <th>Seller</th>
            <th>Top Bid</th>
            <th>Time Remaining</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
    @foreach(var auction in Model)
    {
        <tr>
            <td><a href="ViewAuction/@auction.auction_id">@auction.product_name</a></td>
            <td>@auction.creator.user_name</td>
            <td>$@auction.highest_bid</td>
            <td>@((int)(DateTime.Now - auction.created_at).TotalDays) Day(s)</td>
            <td>
            @{
                if(ViewBag.UserId == auction.user_id)
                {
                    <a href="DeleteAuction/@auction.auction_id">Delete</a>
                }
            }
            </td>
        </tr>
    }
    </tbody>
</table>

Views/Final/ViewAuction.cshtml
<h2>@ViewBag.ViewAuction.product_name</h2>
<h3>Created by: @ViewBag.ViewAuction.creator.user_name</h3>
<p>@ViewBag.ViewAuction.end_date</p>

<p>Highest Bid: $@ViewBag.ViewAuction.highest_bid - By User: 
@{
    string TopBidder = "";
    if(ViewBag.HighestBidder != null)
    {
        TopBidder = ViewBag.HighestBidder.user_name;
    }
    else
    {
        TopBidder = "Starting Bid";
    }
    @TopBidder
}
</p>

@model Bid
<form asp-action="SubmitBid" asp-controller="Final" method="POST">
    <span asp-validation-for="amount" class="form_errors"></span>
    <label asp-for="amount">Amount:</label>
    <input asp-for="amount">

    <button type="submit">Bid</button>
</form>